name = "CosmoCentral"
uuid = "ad8f630a-9b1f-4174-92d0-7638535e3d6b"
authors = ["marcobonici <bonici.marco@gmail.com>"]
version = "0.0.1"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SciPy = "ebc72ef8-9537-4fb0-b64e-ac76025fed2d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Conda = "1.5"
Documenter = "0.26"
DocumenterTools = "0.1"
NumericalIntegration = "0.2"
Parameters = "0.12"
PlotThemes = "2.0"
PyCall = "1.92"
QuadGK = "2.4"
SciPy = "0.1"
