name = "CosmoCentral"
uuid = "ad8f630a-9b1f-4174-92d0-7638535e3d6b"
authors = ["marcobonici <bonici.marco@gmail.com>"]
version = "0.0.2"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
QuadGK = "2.4"
Documenter = "0.26"
