name = "CosmoCentral"
uuid = "ad8f630a-9b1f-4174-92d0-7638535e3d6b"
authors = ["marcobonici <bonici.marco@gmail.com>"]
version = "0.0.2"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LatinHypercubeSampling = "a5e1c1ea-c99a-51d3-a14d-a9a37257b02d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciPy = "ebc72ef8-9537-4fb0-b64e-ac76025fed2d"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Conda = "1.5"
Dierckx = "0.5"
Documenter = "0.26, 0.27"
DocumenterTools = "0.1"
FFTW = "1"
Flux = "0.12, 0.13"
HDF5 = "0.15"
Interpolations = "0.13"
JSON = "0.21"
LoopVectorization = "0.11, 0.12"
NumericalIntegration = "0.2, 0.3"
Parameters = "0.12"
PlotThemes = "2.0"
PlotlyBase = "0.4, 0.5"
PyCall = "1.92"
QuadGK = "2.4"
SciPy = "0.1"
